# Configuration du projet GitHub
name: "Restauration Interactive Backend"
description: "API backend moderne pour restaurants avec commande via QR Code"
url: "https://github.com/votre-username/restauration-interactive-backend"
topics:
  - "restaurant"
  - "qr-code"
  - "api"
  - "express"
  - "mysql"
  - "gabon"
  - "mobile-money"
  - "paiement"
  - "commande"
  - "backend"
  - "nodejs"
  - "jwt"
  - "restauration"
  - "interactive"